### ISSUE TITLE
🎯 Fix Grammer and Spelling Mistakes 🕵

### ISSUE THREAD

**Issue by bauripalash** [bauripalash/article-archive#3]
## 🕵 Description : 
This repository contains my old articles from old blog, most of the Development related articles were exported to DEV.to but some articles were archived here.

## 🎯 Task : 
* Find Grammar and Spelling Mistakes!
* Fork , Make Fixes and Submit a Pull Request!

## ℹ️ Note : 
* One Pull Request Per User is allowed , Otherwise will be marked as `Invalid`. 
* Simple Typo Fixing will be labelled as `Invalid` , user should mention "Little Typos" Here in this thread!
* The Articles are licensed under [Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License](https://creativecommons.org/licenses/by-nc-nd/4.0/)

**Comment by jB1rd0** [comment]
I will work on this
